language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
python: 3.6

env:
    global:
    - LANG="en_US.UTF-8"
    - FC=gfortran-4.8

install:
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.8 gfortran-4.8
    - wget http://launchpadlibrarian.net/229058765/libgsl2_2.1+dfsg-2_amd64.deb  
    - sudo dpkg -i libgsl2_2.1+dfsg-2_amd64.deb
    - wget http://launchpadlibrarian.net/229058764/libgsl-dev_2.1+dfsg-2_amd64.deb
    - sudo dpkg -i libgsl-dev_2.1+dfsg-2_amd64.deb

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make install
     - make unit_test
