language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
python: 3.6

env:
- LANG="en_US.UTF-8"

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make install
     - make unit_test
