language: python
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
python: 3.6

env:
    global:
    - LANG="en_US.UTF-8"
    - FC=gfortran-4.8

install:
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install swig3.0 gcc-4.8 gfortran-4.8 libeigen3-dev libhdf5-dev hdf5-tools libboost-all-dev zlib1g doxygen graphviz
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gsl/libgslcblas0_2.4+dfsg-6_amd64.deb
    - sudo dpkg -i libgslcblas0_2.4+dfsg-6_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gsl/libgsl23_2.4+dfsg-6_amd64.deb
    - sudo dpkg -i libgsl23_2.4+dfsg-6_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gsl/libgsl-dev_2.4+dfsg-6_amd64.deb
    - sudo dpkg -i libgsl-dev_2.4+dfsg-6_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/s/swig/swig3.0_3.0.10-1.2_amd64.deb
    - sudo dpkg -i swig3.0_3.0.10-1.2_amd64.deb

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - ls /usr/lib/x86_64-linux-gnu/libpython3*
     - cmake .. 
     - make
     - make install
     - make unit_test
